:alembic: try a change in the config of rikhuijzer/cache-install to avoid...
```

This derivation is not meant to be built, aborting

builder for '/nix/store/hdyf46sw2s3350khz6s1vw1xqz832l2x-dev-environment.drv' failed with exit code 1
error: build of '/nix/store/hdyf46sw2s3350khz6s1vw1xqz832l2x-dev-environment.drv' failed
```